# IP-Beschraenkung nur fuer Port 80 (Web-GUI)
# Port 7000 bleibt offen fuer PCS
<VirtualHost *:80>
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        AllowOverride All
        Require ip 172.23.56.0/24
        Require ip 192.168.122.0/24
        Require ip 192.168.120.0/24
        Require ip 10.100.10.0/24
        Require ip 10.100.11.0/24
        Require ip 127.0.0.1
    </Directory>
</VirtualHost>
